call plug#begin('~/.vim/autoload')
Plug 'preservim/NERDTree'
call plug#end()
filetype plugin indent on
syntax on
set backspace=indent,eol,start
set hidden
set noswapfile

let $rtp=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
let mapleader =";"
noremap ;; :w<cr>
nmap ,, :bp<cr>
nmap .. :bn<cr>
nmap ;s :source ~/.vimrc<cr>
nmap @@ @:
nmap zz <esc>:w\|:!python3 %<cr>
